# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ml_pb2 as ml__pb2


class RecommendationServiceStub(object):
    """The Recommendation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPersonalizedProducts = channel.unary_unary(
                '/ecommerce.ml.RecommendationService/GetPersonalizedProducts',
                request_serializer=ml__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=ml__pb2.RecommendationResponse.FromString,
                )


class RecommendationServiceServicer(object):
    """The Recommendation service definition.
    """

    def GetPersonalizedProducts(self, request, context):
        """Returns a list of personalized products based on user behavior
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPersonalizedProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalizedProducts,
                    request_deserializer=ml__pb2.RecommendationRequest.FromString,
                    response_serializer=ml__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.ml.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """The Recommendation service definition.
    """

    @staticmethod
    def GetPersonalizedProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ecommerce.ml.RecommendationService/GetPersonalizedProducts',
            ml__pb2.RecommendationRequest.SerializeToString,
            ml__pb2.RecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
