# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x0c\x65\x63ommerce.ml\"\\\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x12\x1d\n\x15interested_categories\x18\x03 \x03(\t\"B\n\rProductDetail\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t\"^\n\x16RecommendationResponse\x12-\n\x08products\x18\x01 \x03(\x0b\x32\x1b.ecommerce.ml.ProductDetail\x12\x15\n\rmodel_version\x18\x02 \x01(\t2}\n\x15RecommendationService\x12\x64\n\x17GetPersonalizedProducts\x12#.ecommerce.ml.RecommendationRequest\x1a$.ecommerce.ml.RecommendationResponseB\x1b\n\x17\x63om.miecommerce.grpc.mlP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.miecommerce.grpc.mlP\001'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=26
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=118
  _globals['_PRODUCTDETAIL']._serialized_start=120
  _globals['_PRODUCTDETAIL']._serialized_end=186
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=188
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=282
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=284
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
