# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x0eintellicart.ml\"\\\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x12\x1d\n\x15interested_categories\x18\x03 \x03(\t\"B\n\rProductDetail\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t\"`\n\x16RecommendationResponse\x12/\n\x08products\x18\x01 \x03(\x0b\x32\x1d.intellicart.ml.ProductDetail\x12\x15\n\rmodel_version\x18\x02 \x01(\t2\x81\x01\n\x15RecommendationService\x12h\n\x17GetPersonalizedProducts\x12%.intellicart.ml.RecommendationRequest\x1a&.intellicart.ml.RecommendationResponseB\x1b\n\x17\x63om.intellicart.grpc.mlP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.intellicart.grpc.mlP\001'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=28
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=120
  _globals['_PRODUCTDETAIL']._serialized_start=122
  _globals['_PRODUCTDETAIL']._serialized_end=188
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=190
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=286
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=289
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
