global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@intellicart.com'
  smtp_auth_username: 'system-alerts@intellicart.com'
  smtp_auth_password: '${SMTP_PASSWORD}' # Inyectado vía ENV
  slack_api_url: '${SLACK_WEBHOOK_URL}'  # Inyectado vía ENV

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  routes:
    # Las alertas críticas van por Slack Y Email
    - match:
        severity: critical
      receiver: 'critical-notifications'
      continue: true

receivers:
  - name: 'default-receiver'
    slack_configs:
      - channel: '#intellicart-alerts'
        send_resolved: true

  - name: 'critical-notifications'
    slack_configs:
      - channel: '#intellicart-critical'
        title: '🚨 CRITICAL ALERT 🚨'
        text: 'Summary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }}'
    email_configs:
      - to: 'architect-on-call@intellicart.com'
        send_resolved: true